# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Analytics with Python & R
email: woosa7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://woosa7.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: webjeda
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/

# Tracker
analytics:

# Comments
disqus-shortname:

#social
facebook: https://www.facebook.com/woosa7
quora:
twitter:
github: https://github.com/woosa7

#facebook like box
fb-app-id:
fb-page-url: https://www.facebook.com/woosa7/
fb-page-title:

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

